### ISSUE TITLE
Retry connect/disconnect after timeout?

### ISSUE THREAD

**Issue by geekdave** [bermi/sauce-connect-launcher#35]
Sometimes SauceConnect just hangs, non-responsive on either the connection or disconnection process.  Would it be possible to set a timeout, and retry the connect/disconnect process if no response received?

**Comment by aearly** [comment]
I just published v0.10.3 which should handle that error output properly.  You then could use something like  [`async.retry`](https://github.com/caolan/async#retry) to try again if that error occurs.

```js
async.retry(3, launchSauceConnect.bind(null, scOptions), function (err) {
  if (err) {
    throw new Error("Sauce Connect failed to launch after 3 retries, error: " + err.message);
  }
  // sauce connect ready
})
```

**Comment by geekdave** [comment]
Still seeing one more instance of an unhandled error:

```
Starting Selenium listener...
Establishing secure TLS connection to tunnel...
Failed to start Selenium listener (exit code 2).
Please check logfile for more information.
Sauce Connect could not establish a connection.
```

This one happens rarely, but often enough to be noticeable, when running multiple tunnels.  PR incoming...
